#####################
#Version Info
#####################
#Plot DOS using the output of split_dos
#DOSplotV1.1.R  20180315
#Plot Total dos and split dos, the input file used by this program is generated by dos_split
#DOSplotV1.2.R  20180316
#Add legend into the figure
#User can specify a set of atom number to view the pdos

#####################
#User defined region
#####################

#Please specify the atom number you want to plot
iAtom<-c(370,400,77,354,394,53,324)

Efermi=1.1131

#-Export figure file type:
#- PDF=1, TIFF=2, EPS=3
FigureType <- 1

#Please specify the system name
SysName <- "406Fix1"

###########
#Main part
###########

print("Note:Plsease run split_dos before running this script")

file1<-"DOS0"
tbl1<-read.table(file1,header=FALSE)
#Plot TDOS
FileName=paste("Fig",SysName,"TDOS",sep="_")
if(FigureType==1){
  pdf(file=paste(FileName,"pdf",sep="."),paper="special",width = 11.69,height = 8.27,bg="white")
}else if(FigureType==2){
  tiff(filename = paste(FileName,"tiff",sep="."),width = 29.7,height =21 ,units ="cm",compression="lzw",bg="white",res=300)
}else if(FigureType==3){
  postscript(file=paste(FileName,"eps",sep="."),paper="special",width = 11.69,height = 8.27,bg="white")  
}
plot(tbl1$V1,tbl1$V2,type="l",xlab="Energy(eV)",ylab="DOS",main="TDOS")
lines(c(Efermi,Efermi),c(min(tbl1$V1)-100,max(tbl1$V2)+100),col="red",lty=2)
legend("topright",legend="TDOS",lty=1,col="black")
dev.off()

for (i in iAtom){
file2<-paste("DOS",i,sep="")
tbl2<-read.table(file2,header=FALSE)

energy<-tbl2$V1
py<-tbl2$V3
pz<-tbl2$V4
px<-tbl2$V5
dxy<-tbl2$V6
dyz<-tbl2$V7
dz2<-tbl2$V8
dxz<-tbl2$V9
dx2<-tbl2$V10
s<-tbl2$V2
p<-tbl2$V3+tbl2$V4+tbl2$V5
d<-tbl2$V6+tbl2$V7+tbl2$V8+tbl2$V9+tbl2$V10
total<-s+p+d


#Plot PDOS
FileName=paste("Fig_",SysName,"_DOS",i,sep="")
if(FigureType==1){
  pdf(file=paste(FileName,"pdf",sep="."),paper="special",width = 11.69,height = 8.27,bg="white")
}else if(FigureType==2){
  tiff(filename = paste(FileName,"tiff",sep="."),width = 29.7,height =21 ,units ="cm",compression="lzw",bg="white",res=300)
}else if(FigureType==3){
  postscript(file=paste(FileName,"eps",sep="."),paper="special",width = 11.69,height = 8.27,bg="white")  
}
plot(energy,s,type="l",xlab="Energy(eV)",ylab="DOS",xlim=c(min(energy),max(energy)),ylim=c(min(min(s),min(p),min(d)),max(max(s),max(p),max(d))))
lines(energy,p,col="blue",lty=6)
lines(energy,d,col="purple",lty=5)
lines(c(Efermi,Efermi),c(min(energy)-100,max(s)+100),col="red",lty=2)
legend("topright",legend=c("s","p","d"),lty=c(1,6,5),col=c("black","blue","purple"))
dev.off()
}